#!/usr/bin/env python 
import os
import sys
import argparse
from os import getcwd
import subprocess as sp
import shutil

# initiate the parser
parser = argparse.ArgumentParser(description="")
parser.add_argument("-s", help="OSt file path", type=str)
parser.add_argument("-o", help="output directory path", default = "./", type=str)
parser.add_argument("-t", help="tt file path", type=str)
parser.add_argument("-ps", help="parallel OSt file path", type=str)
parser.add_argument("-pt", help="parallel tt file path", type=str)
parser.add_argument("--ncpus", help="number of cpues", type=int, default=4,)
# read arguments from the command line
args = parser.parse_args()

#-----------check inputs 


#---------------change giza++/configfile
configfile_path = "./giza++/configfile"
cmd = "sed -i 's/ncpus.*/" +  "ncpus " + str(args.ncpus) + "/' " + configfile_path
print(cmd)
os.system(cmd)

if args.ps != None and os.path.isfile(args.ps) and args.pt != None and os.path.isfile(args.pt):
    ps_line = sum(1 for line in open(args.ps))
    pt_line = sum(1 for line in open(args.pt))
    if ps_line != pt_line:
        print("The number of lines in ", args.ps, " and ", args.pt , " are not equal. please be sure that they are true.")
        sys.exit(1)
    if args.s != None and os.path.isfile(args.s):
        pass
    else:
        print("please use parameter -s <OSt file> or be sure <OSt file> is exist.")
        sys.exit(1)

    if args.t != None and os.path.isfile(args.t):
        pass
    else:
        print("please use parameter -t <tt file> or be sure <tt file> is exist.")
        sys.exit(1)

    s_line = sum(1 for line in open(args.s))
    t_line = sum(1 for line in open(args.t))
    if s_line != t_line:
        print("The number of lines in ", args.s, " and ", args.t , " are not equal. please be sure that they are true.")
        sys.exit(1)
    #--------- make output name
    out_name = args.t.split('/')[-1]
    out_name = args.o + out_name + ".align"

    #-----------run run-giza.sh 

    cmd = "chmod +x run-giza-with-parallel.sh"
    os.system(cmd)
    cmd = "bash run-giza-with-parallel.sh -s " + args.s + " -t " + args.t + " -o " + out_name + " -m " + args.ps + " -n " + args.pt + ";"
    os.system(cmd)


    
else: 
    if args.s != None and os.path.isfile(args.s):
        pass
    else:
        print("please use parameter -s <OSt file> or be sure <OSt file> is exist.")
        sys.exit(1)

    if args.t != None and os.path.isfile(args.t):
        pass
    else:
        print("please use parameter -t <tt file> or be sure <tt file> is exist.")
        sys.exit(1)

    s_line = sum(1 for line in open(args.s))
    t_line = sum(1 for line in open(args.t))
    if s_line != t_line:
        print("The number of lines in ", args.s, " and ", args.t , " are not equal. please be sure that they are true.")
        sys.exit(1)
    #--------- make output name
    out_name = args.t.split('/')[-1]
    out_name = args.o + out_name + ".align"

    #-----------run run-giza.sh 

    cmd = "chmod +x run-giza-without-parallel.sh"
    os.system(cmd)

    cmd = "./run-giza-without-parallel.sh -s " + args.s + " -t " + args.t + " -o " + out_name
    os.system(cmd)




