#!/bin/bash;
python giza++/transcript_to_source.py "$1" > source_ref; 
#concat source_ref and reference with parallel data;
mkdir concat_data;
cat $5 $2 > concat_data/tt_concat;
cat $4 ./source_ref > concat_data/source_concat;
#giza++;
git clone https://github.com/lngvietthang/giza-pp.git; 
cd giza-pp; 
make;
#-------- run giza; 
mkdir run_giza;
cd run_giza;
cp ../../giza++/run.sh  .;
chmod +x run.sh;
cp ../../source_ref .;
cp ../../concat_data/tt_concat tt_concat;
cp ../../concat_data/source_concat source_concat;
#------- run giza;
mkdir out_folder;
./run.sh tt_concat source_concat ./out_folder;
var1=$(wc -l source_ref);
num_line="$(cut -d' ' -f1 <<<"$var1")";
num_line1=$(($num_line * 3));
tail -n $num_line1 out_folder/Result.A3.final > ../../ref_alignment;
cd ../../;
#-------- mwerSegmenter;
chmod +x mwerSegmenter ;
#-------- run sltev; 
python SLTev.py --ostt $1 --tt $2 --mt $3 --align ref_alignment --b_time 3000;
