#!/usr/bin/env python 
import os
import sys
import argparse


# initiate the parser
parser = argparse.ArgumentParser(description="")
parser.add_argument("-s", help="OSt file path", type=str)
parser.add_argument("-o", help="output directory path", default = "./", type=str)
parser.add_argument("-t", help="tt file path", type=str)
parser.add_argument("-ps", help="parallel OSt file path", type=str)
parser.add_argument("-pt", help="parallel tt file path", type=str)
parser.add_argument("--ncpus", help="number of cpues", type=int, default=4,)
args = parser.parse_args()

# print to STDERR:
def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)
    
    
#check output directory
if os.path.isdir(args.o):
    out_dir = args.o
else:
    os.makedirs(args.o, exist_ok=True)
    out_dir = args.o
#---------------change giza++/configfile
configfile_path = "./giza++/configfile"
cmd = "sed -i 's/ncpus.*/" +  "ncpus " + str(args.ncpus) + "/' " + configfile_path
eprint(cmd)
os.system(cmd)

#check input files
if args.s != None and os.path.isfile(args.s):
    pass
else:
    eprint("please use parameter -s <OSt file> or be sure <OSt file> is exist.")
    sys.exit(1)

if args.t != None and os.path.isfile(args.t):
    pass
else:
    eprint("please use parameter -t <tt file> or be sure <tt file> is exist.")
    sys.exit(1)

s_line = sum(1 for line in open(args.s))
t_line = sum(1 for line in open(args.t))
if s_line != t_line:
    eprint("The number of lines in ", args.s, " and ", args.t , " are not equal. please be sure that they are true.")
    sys.exit(1)
    
path, target_name = os.path.split(args.t)
target_language = target_name.split('.')[-2]
path, source_name = os.path.split(args.s)
out_name = out_dir + '.'.join(source_name.split('.')[:-1]) + '.' + target_language + ".align"

if args.ps != None and os.path.isfile(args.ps) and args.pt != None and os.path.isfile(args.pt):
    ps_line = sum(1 for line in open(args.ps))
    pt_line = sum(1 for line in open(args.pt))
    if ps_line != pt_line:
        eprint("The number of lines in ", args.ps, " and ", args.pt , " are not equal. please be sure that they are true.")
        sys.exit(1)
    cmd = "bash run-giza-with-parallel.sh -s " + args.s + " -t " + args.t + " -o " + out_name + " -m " + args.ps + " -n " + args.pt + ";"
    os.system(cmd)    
else: 
    cmd = "./run-giza-without-parallel.sh -s " + args.s + " -t " + args.t + " -o " + out_name
    os.system(cmd)





